substitutions:
  _IMAGE_NAME: your-image-name
  _SERVICE_NAME: edmonbrain-unstructured
  _REGION: your-region
  _SERVICE_ACCOUNT: your-service@your-project.iam.gserviceaccount.com

steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: unstructured
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}/unstructured', '-f', 'Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}/unstructured']

  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy cloud run
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud run deploy ${_SERVICE_NAME} --image gcr.io/$PROJECT_ID/${_IMAGE_NAME}/unstructured \
           --region ${_REGION} \
           --platform managed \
           --allow-unauthenticated \
           --memory 8Gi \
           --cpu 4 \
           --min-instances 0 \
           --max-instances 3 \
           --service-account ${_SERVICE_ACCOUNT} \
           --timeout=20m